/* Copyright © 2024 Georgy E. All rights reserved. */


#include <stdint.h>

#include "bmp.h"
#include "display.h"


#define BMP_UP_15x15_HEIGHT (15)
#define BMP_UP_15x15_WIDTH  (15)
#define _COLOR              (DISPLAY_COLOR_BLACK)
#define _BCKGR              (DISPLAY_COLOR_WHITE)

const BITMAPSTRUCT bmp_up_15x15 __attribute__((aligned)) =
{
	{
		0x4d42u,
		sizeof(BITMAPINFOHEADER) + sizeof(BITMAPFILEHEADER) + (BMP_UP_15x15_WIDTH * BMP_UP_15x15_HEIGHT * 2),
		0x0000u,
		0x0000u,
		sizeof(BITMAPINFOHEADER) + sizeof(BITMAPFILEHEADER)
	},
	{
		sizeof(BITMAPINFOHEADER),
		BMP_UP_15x15_WIDTH,
		BMP_UP_15x15_HEIGHT,
		1u,
		16,
		0x00000003u,
		(BMP_UP_15x15_WIDTH * BMP_UP_15x15_HEIGHT),
		0x00000000ul,
		0x00000000ul,
		0x00000000ul,
		0x00000000ul
	},
	{
		_COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR,
		_COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR,
		_BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR,
		_BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR,
		_BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR
	}
};

#undef _COLOR


#define BMP_DOWN_15x15_HEIGHT (15)
#define BMP_DOWN_15x15_WIDTH  (15)
#define _COLOR                (DISPLAY_COLOR_BLACK)

const BITMAPSTRUCT bmp_down_15x15 __attribute__((aligned)) =
{
	{
		0x4d42u,
		sizeof(BITMAPINFOHEADER) + sizeof(BITMAPFILEHEADER) + (BMP_UP_15x15_WIDTH * BMP_UP_15x15_HEIGHT * 2),
		0x0000u,
		0x0000u,
		sizeof(BITMAPINFOHEADER) + sizeof(BITMAPFILEHEADER)
	},
	{
		sizeof(BITMAPINFOHEADER),
		BMP_UP_15x15_WIDTH,
		BMP_UP_15x15_HEIGHT,
		1u,
		16,
		0x00000003u,
		(BMP_UP_15x15_WIDTH * BMP_UP_15x15_HEIGHT),
		0x00000000ul,
		0x00000000ul,
		0x00000000ul,
		0x00000000ul
	},
	{
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR,
		_BCKGR, _BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR, _BCKGR,
		_BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR,
		_BCKGR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _BCKGR,
		_COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR,
		_COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR, _COLOR
	}
};

#undef _COLOR
